CREATE TABLE IF NOT EXISTS ALUNO (
  ID BIGINT(20) NOT NULL,
  NOME VARCHAR(255) DEFAULT NULL,
  SERIE VARCHAR(255) DEFAULT NULL,
  STATUS VARCHAR(255) DEFAULT NULL,
  REPOSANVEL_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FKLKUIMQ8S8WJTRY3GQ54FDG9YC (REPOSANVEL_ID)
);

CREATE TABLE IF NOT EXISTS COMUNICADO (
  ID BIGINT(20) NOT NULL,
  TEXTO VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS NOTA (
  ID BIGINT(20) NOT NULL,
  NOTA DECIMAL(19,2) DEFAULT NULL,
  ALUNO_ID BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK7NTSGEM4QL46UY34ILE14RG74 (ALUNO_ID)
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL (
  ID BIGINT(20) NOT NULL,
  NOME VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

